### ISSUE TITLE
use Router and StateManager

### ISSUE THREAD

**Issue by icholy** [icholy/ember-brunch#1]
Update the boilerplate to use the statemanager/states and the new router.

**Comment by edubkendo** [comment]
Will be really glad when you update this. The router on the latest versions of ember simplifies everything so much. I think this is an awesome project btw, and appreciate your efforts.

**Comment by edubkendo** [comment]
http://emberjs.com/blog/2012/08/03/ember-1-0-prerelease/

**Comment by icholy** [comment]
I'm on it

**Comment by wonk** [comment]
Please update for node 0.8 as well.  The ember-brunch package.json does not currently allow installation under node 0.8.x.
And css--brunch errors with incompatible version (needs update to allow 1.3.0, I think).
Not sure what other versioning issues exist.

Thx.

**Comment by icholy** [comment]
yesir

**Comment by icholy** [comment]
@edubkendo take a look at the [router](https://github.com/icholy/ember-brunch/tree/router) branch. What do you think I should add?

@wonk pls create a new issue

**Comment by icholy** [comment]
PR's are completely welcome btw

**Comment by icholy** [comment]
merged into master

**Comment by edubkendo** [comment]
Sorry, missed this somehow. I should have gotten emails, but I wonder if github's recent changes messed that up somehow. Anyways, will give this a try soon and report any feedback

**Comment by icholy** [comment]
sounds good. I actually haven't used the Router in any real applications yet, so let me know if you see anything funky.

**Comment by icholy** [comment]
do you think the router should be split across multiple files?

**Comment by edubkendo** [comment]
I am currently using ember in a fairly large project, taking advantage of the router, and so far I've kept the router in one file, because even though it could potentially get long-ish, it's much easier to follow the logic with it all there together. Keeping up with all those transitions and outlets would get a bit tricky otherwise, I think.

**Comment by icholy** [comment]
Alright, well I'm starting a large app with this new skeleton. I'll see what works.
