### ISSUE TITLE
Script for updating Ember from source

### ISSUE THREAD

**Issue by vojto** [icholy/ember-brunch#14]
Hey guys,

Here's a little script, that clones Ember repo, makes a build and copies it to vendor/. Tell me if you like it and I can submit a pull request, or you can just copy it in the repo, I don't care. :)

https://github.com/vojto/ember-brunch/commit/79a3d274d798bea998981704c34de380e2706ddd

**Comment by icholy** [comment]
I'm lazy, open a PR. Would be better if it was a js script though. That way it would be portable.

**Comment by icholy** [comment]
added 292733357a14c05b76e237e93b47e37d619e08a8 thanks
