### ISSUE TITLE
upgrading to latest ember-brunch build 

### ISSUE THREAD

**Issue by joshua1** [icholy/ember-brunch#17]
Hi icholy, 
please how do i update my existing application to use the latest ember-brunch build.i will appreciate it if you can outline the way to go about that.
Thanks,
Joshua

**Comment by icholy** [comment]
what version of ember are you using?

**Comment by joshua1** [comment]
i am using 1.0.0.0 pre 2. and i observed some major changes with the ember-brunch for pre 4

**Comment by icholy** [comment]
ember-brunch changed a lot because ember changed a lot.
This skeleton hasn't really changed too much in the way it works.

https://github.com/icholy/ember-handlebars-brunch is the only thing that really changed. 
see https://github.com/icholy/ember-handlebars-brunch/pull/4 

Have you read through the new [guides](http://emberjs.com/guides/) yet?

**Comment by joshua1** [comment]
I have read the guides, i am even using your latest ember-brunch build and was having the templateName and template issues too. with the link you sent i have fixed that, but when i do a transitionTo('public.home'); in my index router class, i get this error

Uncaught TypeError: Object function (context, options) {
      options = options || {};
      return templateSpec.call(container, Handlebars, context, options.helpers, options.partials, options.data);
    } has no method 'indexOf' 

if i change the URL to just home (which is a nested route in public) , it throws, the route home was not found

**Comment by joshua1** [comment]
I have gotten past the issue i just mentioned above still had to do with templateName, although my nested route and the resource templates are not loading in my application template, i just get a blank at the moment.

**Comment by icholy** [comment]
If I understand correctly, that template should live in `app/templates/public/home.hbs`. 
Then it should end up in `App.TEMPLATES['public/home']`

also, make sure you have the `root` property in your config.
https://github.com/icholy/ember-brunch/blob/empty/config.coffee#L34

**Comment by joshua1** [comment]
yes thats where the template lives, i also have the root property in my config.coffee file, should i have the template for public also in the public folder, as that doesn't render too (home is supposed to render in the outlet of the public template)

**Comment by joshua1** [comment]
Thanks icholy, I finally got it working.i hope i dont get into any issues again. you have been of great help.thanks a lot

**Comment by icholy** [comment]
awesome!
